### ISSUE TITLE
Not sure how to get new shows

### ISSUE THREAD

**Issue by Trevoke** [JDiPierro/tmsapi#2]
Soooo here's what I did after successfully trying your movies example:

```
[7] pry(main)> new_shows = tms.programs.new_shows
ArgumentError: wrong number of arguments (0 for 1)
from /Users/aldric/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/tmsapi-0.1.0/lib/tmsapi/resource/programs.rb:30:in `new_shows'
[8] pry(main)> new_shows = tms.programs.new_shows(lineupId: 'USA-TX42500-X', startDateTime: Time.now)

Faraday::Error::ClientError: the server responded with status 400
from /Users/aldric/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.8.9/lib/faraday/response/raise_error.rb:11:in `on_complete'
[9] pry(main)> new_shows = tms.programs.new_shows({})Faraday::Error::ClientError: the server responded with status 400
from /Users/aldric/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.8.9/lib/faraday/response/raise_error.rb:11:in `on_complete'
[10] pry(main)> new_shows = tms.programs.new_shows(lineupId: 'USA-TX42500-X', startDateTime: Time.now)
```

I'm a bit confused and some help would be most welcome!

**Comment by JDiPierro** [comment]
Hey Trevoke,

Right now the startDateTime parameter needs you to format it yourself. If you change your `Time.now` to `Time.now.strftime("%Y-%m-%dT%H:%MZ")` it should work. Alternatively if no startDateTime is provided it will default to `Time.now` with the proper formatting so you can just leave that out and it should work.

I'm going to leave this issue open and I'll look into having the endpoints auto-format the startDateTime so the user doesn't have to.

Thanks for using the gem, and for submitting the first issue :D
Justin
